/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 28-Jun-2025 17:00:15
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /home/caccolillo/matlab_2021b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const int32_T NUM[MWSPT_NSEC][3] = {
  {
       9722799,           0,           0 
  },
  {
    2147483647,           0, -2147483648 
  },
  {
       9722799,           0,           0 
  },
  {
    2147483647,           0, -2147483648 
  },
  {
       9700913,           0,           0 
  },
  {
    2147483647,           0, -2147483648 
  },
  {
    2147483647,           0,           0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const int32_T DEN[MWSPT_NSEC][3] = {
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  2137155102 
  },
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  2138366919 
  },
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  2128081823 
  },
  {
    2147483647,           0,           0 
  }
};
