/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 29-Jun-2025 20:17:00
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * /home/caccolillo/matlab_2021b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const int32_t NUM[MWSPT_NSEC][3] = {
  {
       2445277,           0,           0 
  },
  {
    2147483647,  2147483647,  2147483647 
  },
  {
       2397414,           0,           0 
  },
  {
    2147483647,  2147483647,  2147483647 
  },
  {
       2358150,           0,           0 
  },
  {
    2147483647,  2147483647,  2147483647 
  },
  {
       2330420,           0,           0 
  },
  {
    2147483647,  2147483647,  2147483647 
  },
  {
       2316102,           0,           0 
  },
  {
    2147483647,  2147483647,  2147483647 
  },
  {
    2147483647,           0,           0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const int32_t DEN[MWSPT_NSEC][3] = {
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  2102404037 
  },
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  2019218264 
  },
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  1950977521 
  },
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  1902783186 
  },
  {
    2147483647,           0,           0 
  },
  {
    2147483647, -2147483648,  1877897715 
  },
  {
    2147483647,           0,           0 
  }
};


